In [18]:
import csv
from jobspy import scrape_jobs

jobs = scrape_jobs(
    site_name=["linkedin"], # "glassdoor", "bayt", "naukri", "bdjobs"
    search_term="Data engineer",
    # google_search_term="software engineer jobs near San Francisco, CA since yesterday",
    location="Netherlands",
    results_wanted=10,
    hours_old=72,
    country_indeed='Netherlands',
    
    linkedin_fetch_description=True # gets more info such as description, direct job url (slower)

)
print(f"Found {len(jobs)} jobs")
print(jobs.head())
jobs.to_csv("jobs.csv", quoting=csv.QUOTE_NONNUMERIC, escapechar="\\", index=False) # to_excel

Found 10 jobs
              id      site                                        job_url  \
0  li-4374244548  linkedin  https://www.linkedin.com/jobs/view/4374244548
1  li-4376581340  linkedin  https://www.linkedin.com/jobs/view/4376581340
2  li-4375346755  linkedin  https://www.linkedin.com/jobs/view/4375346755
3  li-4374559187  linkedin  https://www.linkedin.com/jobs/view/4374559187
4  li-4376572806  linkedin  https://www.linkedin.com/jobs/view/4376572806

                                      job_url_direct                   title  \
0  https://grnh.se/755cb9wt1us?source=LinkedIn&ur...  Graduate Data Engineer
1                                                NaN           Data Engineer
2                                                NaN           Data Engineer
3                                                NaN           Data Engineer
4                                                NaN           Data Engineer

        company                               location date_posted  job_type  \
0  Flow Traders  Amsterdam, North Holland, Netherlands  2026-02-23  fulltime
1  Radley James  Amsterdam, North Holland, Netherlands  2026-02-23  fulltime
2  CIMSOLUTIONS             North Holland, Netherlands  2026-02-23  fulltime
3  Tech phoenix                                                NaN  fulltime
4   E-Solutions                                                NaN  contract

  salary_source  ... company_addresses company_num_employees company_revenue  \
0          None  ...              None                  None            None
1          None  ...              None                  None            None
2          None  ...              None                  None            None
3          None  ...              None                  None            None
4          None  ...              None                  None            None

  company_description  skills experience_range company_rating  \
0                None    None             None           None
1                None    None             None           None
2                None    None             None           None
3                None    None             None           None
4                None    None             None           None

  company_reviews_count vacancy_count work_from_home_type
0                  None          None                None
1                  None          None                None
2                  None          None                None
3                  None          None                None
4                  None          None                None

[5 rows x 34 columns]

In [2]:
import database

# 1. This ensures jobs.db exists and has the correct table
database.init_db()

# ... run your JobSpy extraction here to get a dataframe [jobs](cci:1://file:///Users/levi/Linkedin-notifier/database.py:25:0-61:68) ...

# 2. Save the dataframe directly to the database
database.save_jobs(jobs)

# 3. Read it back anytime to view your saved jobs
saved_jobs_df = database.get_all_jobs()
saved_jobs_df.head()

No new jobs to add (all were duplicates).

,id,site,job_url,title,company
0,1,a,c,e,g
1,2,b,d,f,h
2,li-4374244548,linkedin,https://www.linkedin.com/jobs/view/4374244548,Graduate Data Engineer,Flow Traders
3,li-4376581340,linkedin,https://www.linkedin.com/jobs/view/4376581340,Data Engineer,Radley James
4,li-4375346755,linkedin,https://www.linkedin.com/jobs/view/4375346755,Data Engineer,CIMSOLUTIONS

In [15]:
import database
import importlib
importlib.reload(database)

database.get_latest_batch_jobs()

,id,site,job_url,title,company,batch_id
0,li-4374244548,linkedin,https://www.linkedin.com/jobs/view/4374244548,Graduate Data Engineer,Flow Traders,1
1,li-4376581340,linkedin,https://www.linkedin.com/jobs/view/4376581340,Data Engineer,Radley James,1
2,li-4375346755,linkedin,https://www.linkedin.com/jobs/view/4375346755,Data Engineer,CIMSOLUTIONS,1
3,li-4375347681,linkedin,https://www.linkedin.com/jobs/view/4375347681,Data Engineer,CIMSOLUTIONS,1
4,li-4240310364,linkedin,https://www.linkedin.com/jobs/view/4240310364,Software Engineer I - Backend,Booking.com,1
...,...,...,...,...,...,...
84,li-4368772279,linkedin,https://www.linkedin.com/jobs/view/4368772279,Business Intelligence Professional,Team EIFFEL,1
85,li-4374590669,linkedin,https://www.linkedin.com/jobs/view/4374590669,Maintenance Engineer,LEV hr-professionals,1
86,li-4315508760,linkedin,https://www.linkedin.com/jobs/view/4315508760,Lead Mechanical Engineer (MCF/ Data Centres),Haskoning,1
87,li-4368767436,linkedin,https://www.linkedin.com/jobs/view/4368767436,Werkondernemer Analytics,Team EIFFEL,1
88,li-4377191340,linkedin,https://www.linkedin.com/jobs/view/4377191340,Operations Research Analyst - Global Finance,ABN AMRO Bank N.V.,1

KeyError: 'GMN_API_KEY'